import Head from 'next/head'
import Brand from '../src/components/Brand'
import Multi from '../src/components/Slider/Multi'
import Single from '../src/components/Slider/Single'
import { listItems } from '../data/data'
export default function Home() {
  const data = [
    {
      id: 'tasteePOS',
      brandId: 'tasteePOS',
      brandName: 'tasteePOS',
      image: 'https://tastee-test.s3.ap-southeast-1.amazonaws.com/images/brand/b44ee411-7214-4914-a040-9d63250fc4de/u2qmimif.t5319102022163049.png'
    },
    {
      id: 'Thaotv1',
      brandId: 'Thaotv1',
      brandName: 'Thaotv1',
      image: 'https://tastee-test.s3.ap-southeast-1.amazonaws.com/images/brand/89f2ecba-fb87-424e-a543-8f1e76bc1d9f/q2g1yyr2.btl03122022201655.png'
    },
    {
      id: '0909000008',
      brandId: '0909000008',
      brandName: '0909000008',
      image: 'https://tastee-test.s3.ap-southeast-1.amazonaws.com/images/decoration/2fe88620-8ce9-4bfb-b3e0-2791fc14aeb5/dztz2cvv.kmf08102022143912.file'
    },
    {
      id: 'tasteePOS01',
      brandId: 'tasteePOS',
      brandName: 'tasteePOS',
      image: 'https://tastee-test.s3.ap-southeast-1.amazonaws.com/images/brand/b44ee411-7214-4914-a040-9d63250fc4de/u2qmimif.t5319102022163049.png'
    },
    {
      id: 'Thaotv102',
      brandId: 'Thaotv1',
      brandName: 'Thaotv1',
      image: 'https://tastee-test.s3.ap-southeast-1.amazonaws.com/images/brand/89f2ecba-fb87-424e-a543-8f1e76bc1d9f/q2g1yyr2.btl03122022201655.png'
    },
    {
      id: '090900000802',
      brandId: '0909000008',
      brandName: '0909000008',
      image: 'https://tastee-test.s3.ap-southeast-1.amazonaws.com/images/decoration/2fe88620-8ce9-4bfb-b3e0-2791fc14aeb5/dztz2cvv.kmf08102022143912.file'
    },
   
  ]
  return (
    <div>
      <Head>
        <title>Tastee</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Brand text='thương hiệu nổi tiếng'>
          <Multi />
          <hr />
        </Brand>
        <Brand text='sản phẩm nổi bật'>
          {/* <ul className='brand-select'>
            <li>nước hoa nam</li>
            <li>nước hoa nữ</li>
            <li>nước hoa unisex</li>
          </ul> */}
          <Single data={data}/>
        </Brand>
      </main>
    </div>
  )
}
